# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RandomImage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RandomImage
  pod "PromiseKit", "~> 6.0"

  target 'RandomImageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RandomImageUITests' do
    # Pods for testing
  end

end
